TITLE:RECURSION
MENU_SCRIPT:scripts/menu.lua
SCRIPT:scripts/main.lua
DIALOG_END_INDICATOR:res/misc/circle.png
DIALOG_BOX:res/misc/TEX#win_02b.PNG
FALLBACK_FONT:res/font_en.png
ICON:res/icon.png
DEV_SCREEN_WIDTH:1024
DEV_SCREEN_HEIGHT:768
SCREEN_WIDTH:1024
SCREEN_HEIGHT:768
DEFAULT_FULLSCREEN:false