SCRIPT:scripts/SA00.lua
TITLE:Remember11 - Self Chapter
DIALOG_END_INDICATOR:res/misc/circle.png
DIALOG_BOX:res/misc/TEX#win_01b.PNG
CHOICE_BOX:res/misc/TEX#win_00b.PNG
FALLBACK_FONT:res/font_en.png
ICON:res/icon.png