TITLE:Remember11 -the age of infinity-
MENU_SCRIPT:scripts/n.lua
SCRIPT:scripts/test.hbs
DIALOG_END_INDICATOR:res/misc/circle.png
DIALOG_BOX:res/misc/TEX#win_02b.PNG
FALLBACK_FONT:res/font_en.png
ICON:res/icon.png
DEV_SCREEN_WIDTH:1280
DEV_SCREEN_HEIGHT:960
SCREEN_WIDTH:1280
SCREEN_HEIGHT:960
DEFAULT_FULLSCREEN:false